# experiment name
EXP_NAME: RRDBNet_x4-DFO2K
# random number seed
SEED: 0
# super resolution magnification factor
SCALE: 4
# run device model
DEVICE_ID: 0

# Model define
MODEL:
  EMA:
    ENABLE: True
    DECAY: 0.999
    COMPILED: True
  G:
    NAME: rrdbnet_x4
    IN_CHANNELS: 3
    OUT_CHANNELS: 3
    CHANNELS: 64
    GROWTH_CHANNELS: 32
    NUM_RRDB: 23
    COMPILED: True

TRAIN:
  DATASET:
    TRAIN_GT_IMAGES_DIR: ./data/DFO2K_train_GT

    GT_IMAGE_SIZE: 192

  # Model file address, used for pre-training and recovery training
  CHECKPOINT:
    PRETRAINED_G_MODEL: ""
    RESUMED_G_MODEL: ""

  # training hyperparameters
  HYP:
    IMGS_PER_BATCH: 16
    SHUFFLE: True
    NUM_WORKERS: 4
    PIN_MEMORY: True
    PERSISTENT_WORKERS: True

    EPOCHS: 67  # 238907 images, 1000000 iters

  OPTIM:
    NAME: Adam
    LR: 0.0002
    BETAS: [0.9, 0.999]
    EPS: 0.0001
    WEIGHT_DECAY: 0.0

  LR_SCHEDULER:
    NAME: StepLR
    STEP_SIZE: 34
    GAMMA: 0.5

  # Loss function
  LOSSES:
    PIXEL_LOSS:
      NAME: L1Loss
      WEIGHT: [1.0]

  PRINT_FREQ: 100

TEST:
  DATASET:
    PAIRED_TEST_GT_IMAGES_DIR: "./data/Set5/X4/GT"
    PAIRED_TEST_LR_IMAGES_DIR: "./data/Set5/X4/LR"

  # Test hyperparameters
  HYP:
    IMGS_PER_BATCH: 1
    SHUFFLE: False
    NUM_WORKERS: 1
    PIN_MEMORY: True
    PERSISTENT_WORKERS: True

  # Only test Y channel
  ONLY_TEST_Y_CHANNEL: True

  SAVE_IMAGE_DIR: ""
