# Copyright 2020 Dakewe Biotech Corporation. All Rights Reserved.
# Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================
import torch.nn as nn
import torchvision.models


class PerceptualLoss(nn.Module):
    r"""Perception loss function of esrgan based on VGG19"""
    def __init__(self):
        super(PerceptualLoss, self).__init__()

        vgg = torchvision.models.vgg19(pretrained=True)
        model = nn.Sequential(*list(vgg.features)[:35]).eval()
        for param in model.parameters():
            param.requires_grad = False
        self.model = model
        self.l1_loss = nn.L1Loss()

    def forward(self, src_img, dst_img):
        r"""
        
        Args:
            src_img (array): High resolution image generated by generator.
            dst_img (array): High resolution source image from sample.

        """
        perception_loss = self.l1_loss(self.model(src_img), self.model(dst_img))
        return perception_loss
